// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgrOhiqZwZvQjP4c0FwGPTsiqJxpnewI',
    appId: '1:471839615077:web:3befa2081d64cee5447e8c',
    messagingSenderId: '471839615077',
    projectId: 'chat-app-53cbb',
    authDomain: 'chat-app-53cbb.firebaseapp.com',
    storageBucket: 'chat-app-53cbb.firebasestorage.app',
    measurementId: 'G-N00M18YQ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqVvESSDhpQ_T-QfJX8loaUYOdMy9yY8',
    appId: '1:471839615077:android:916e021531133c86447e8c',
    messagingSenderId: '471839615077',
    projectId: 'chat-app-53cbb',
    storageBucket: 'chat-app-53cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuxzjGAO6zpDvBu_P6axybuwOm_NtReo',
    appId: '1:471839615077:ios:f234d30fac5264ee447e8c',
    messagingSenderId: '471839615077',
    projectId: 'chat-app-53cbb',
    storageBucket: 'chat-app-53cbb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuxzjGAO6zpDvBu_P6axybuwOm_NtReo',
    appId: '1:471839615077:ios:f234d30fac5264ee447e8c',
    messagingSenderId: '471839615077',
    projectId: 'chat-app-53cbb',
    storageBucket: 'chat-app-53cbb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkgrOhiqZwZvQjP4c0FwGPTsiqJxpnewI',
    appId: '1:471839615077:web:5a83cf9aaa97ed14447e8c',
    messagingSenderId: '471839615077',
    projectId: 'chat-app-53cbb',
    authDomain: 'chat-app-53cbb.firebaseapp.com',
    storageBucket: 'chat-app-53cbb.firebasestorage.app',
    measurementId: 'G-1MD5Y2V5CD',
  );
}
